StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/model/Customer.java
package com.suthar.rentel.domain.model;

import com.suthar.rentel.domain.strategy.ChargeStrategy;
import com.suthar.rentel.domain.strategy.RewardPointsStrategy;

import javax.persistence.*;
import java.util.Set;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
@Entity
@Table
public class Customer {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    @Column
    private String name;

    public Customer() {
    }

    public long getId() {
        return id;
    }

    public Customer(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public String statement(final Set<Rental> newRentals) {
        String result = "Rental Record for " + getName() + "\n";

        double totalAmount = 0;
        double totalRewardPoints = 0;
        for (Rental rental : newRentals) {
            // show figures for this rental
            final int rentalDays = rental.getRentedForDays();

            double charge = ChargeStrategy.getCharge(rental.getMovie().getType(), rentalDays);
            result += "  " + rental.getMovie().getTitle() + "  -  $"
                    + String.valueOf(charge) + "\n";
            totalAmount += charge;
            totalRewardPoints += RewardPointsStrategy.getRewardPoints(rental.getMovie().getType(), rentalDays);
        }

        // add footer lines
        result += "Amount charged is $" + String.valueOf(totalAmount) + "\n";
        result += "Total Reward Points is " + String.valueOf(totalRewardPoints);
        return result;
    }

}

StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/model/Movie.java
package com.suthar.rentel.domain.model;

import javax.persistence.*;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
@Entity
@Table
public class Movie {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    @Column
    private String title;
    @Column
    private MovieType type;

    public Movie() {
    }

    public Movie(String title, MovieType type) {
        this.title = title;
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public MovieType getType() {
        return type;
    }

    public long getId() {
        return id;
    }
}

StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/model/MovieType.java
package com.suthar.rentel.domain.model;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
public enum MovieType {
    NEW("NEW MOVIE"),
    OLD("OLD MOVIE"),
    CLASSICAL("CLASSICAL MOVIE");

    MovieType(String type) {

    }
}

StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/model/Rental.java
package com.suthar.rentel.domain.model;

import org.joda.time.LocalDateTime;
import org.joda.time.Period;

import javax.persistence.*;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
@Entity
@Table
public class Rental {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;
    @OneToOne
    private Movie movie;
    @OneToOne
    private Customer customer;
    @Column
    private LocalDateTime rentedOn;
    @Column
    private int rentedForDays;
    @Column
    public boolean returnStatus;

    public Rental() {
    }

    public Rental(Customer customer, Movie movie, int rentedForDays, LocalDateTime rentedOn) {
        this.movie = movie;
        this.customer = customer;
        this.rentedForDays = rentedForDays;
        this.rentedOn = rentedOn;
        this.returnStatus = false;
    }

    public Movie getMovie() {
        return movie;
    }

    public Customer getCustomer() {
        return customer;
    }

    public int getRentedForDays() {
        return rentedForDays;
    }

    public LocalDateTime getRentedOn() {
        return rentedOn;
    }

    public LocalDateTime getEndDate() {
        return rentedOn.plus(Period.days(rentedForDays));
    }

    public boolean isReturned() {
        return returnStatus;
    }

    public void setReturn() {
        this.returnStatus = true;
    }
}

StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/model/Transaction.java
package com.suthar.rentel.domain.model;

import org.joda.time.LocalDateTime;

import java.util.Collections;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
public class Transaction {
    private final LocalDateTime dateTime;
    private final Customer customer;
    private final Set<Rental> rentals;

    public Transaction(final LocalDateTime dateTime, final Customer customer, final Set<Rental> rentals) {
        this.dateTime = dateTime;
        for (final Rental rental : rentals) {
            if (!rental.getCustomer().equals(customer)) {
                throw new IllegalArgumentException("Rentals must be for the same customer");
            }
        }
        this.customer = customer;
        this.rentals = Collections.unmodifiableSet(new HashSet<Rental>(rentals));
    }

    public LocalDateTime getDateTime() {
        return dateTime;
    }

    public Customer getCustomer() {
        return customer;
    }

    public Set<Rental> getRentals() {
        return rentals;
    }

    public static Comparator<Transaction> TX_COMPARE_DATE_TIME = new Comparator<Transaction>() {

        @Override
        public int compare(final Transaction transaction1, final Transaction transaction2) {
            return transaction1.getDateTime().compareTo(transaction2.getDateTime());
        }
    };
}

StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/repository/CustomerRepository.java
package com.suthar.rentel.domain.repository;

import com.suthar.rentel.domain.model.Customer;
import com.suthar.rentel.domain.specification.Specification;
import com.suthar.rentel.domain.util.NonUniqueObjectSelectedException;
import com.suthar.rentel.domain.util.NullObjectAddedException;

import java.util.Collection;
import java.util.Comparator;
import java.util.List;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
public interface CustomerRepository {
    void add(Customer entity) throws NullObjectAddedException;

    void add(Collection<Customer> entities) throws NullObjectAddedException;

    List<Customer> selectAll();

    List<Customer> selectAll(Comparator<Customer> comparator);

    List<Customer> selectSatisfying(Specification<Customer> specification);

    List<Customer> selectSatisfying(Specification<Customer> specification, Comparator<Customer> comparator);

    Customer selectUnique(Specification<Customer> specification) throws NonUniqueObjectSelectedException;
}

StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/repository/MovieRepository.java
package com.suthar.rentel.domain.repository;

import com.suthar.rentel.domain.model.Movie;
import com.suthar.rentel.domain.specification.Specification;
import com.suthar.rentel.domain.util.NonUniqueObjectSelectedException;
import com.suthar.rentel.domain.util.NullObjectAddedException;

import java.util.Collection;
import java.util.Comparator;
import java.util.List;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
public interface MovieRepository {
    void add(Movie entity) throws NullObjectAddedException;

    void add(Collection<Movie> entities) throws NullObjectAddedException;

    List<Movie> selectAll();

    List<Movie> selectAll(Comparator<Movie> comparator);

    List<Movie> selectSatisfying(Specification<Movie> specification);

    List<Movie> selectSatisfying(Specification<Movie> specification, Comparator<Movie> comparator);

    Movie selectUnique(Specification<Movie> specification) throws NonUniqueObjectSelectedException;

    List<Movie> withTitles(String... titles);
}

StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/repository/RentalRepository.java
package com.suthar.rentel.domain.repository;

import com.suthar.rentel.domain.model.Customer;
import com.suthar.rentel.domain.model.Movie;
import com.suthar.rentel.domain.model.Rental;
import com.suthar.rentel.domain.specification.Specification;
import com.suthar.rentel.domain.util.NonUniqueObjectSelectedException;
import com.suthar.rentel.domain.util.NullObjectAddedException;

import java.util.Collection;
import java.util.Comparator;
import java.util.List;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
public interface RentalRepository {
    void add(Rental entity) throws NullObjectAddedException;

    void add(Collection<Rental> entities) throws NullObjectAddedException;

    List<Rental> selectAll();

    List<Rental> selectAll(Comparator<Rental> comparator);

    List<Rental> selectSatisfying(Specification<Rental> specification);

    List<Rental> selectSatisfying(Specification<Rental> specification, Comparator<Rental> comparator);

    Rental selectUnique(Specification<Rental> specification) throws NonUniqueObjectSelectedException;

    List<Rental> currentRentalsFor(Customer customer);

    Rental findRental(Movie movie);
}

StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/repository/SetBasedCustomerRepository.java
package com.suthar.rentel.domain.repository;

import com.suthar.rentel.domain.model.Customer;
import com.suthar.rentel.domain.service.CustomerService;
import com.suthar.rentel.domain.specification.Specification;
import com.suthar.rentel.domain.util.NonUniqueObjectSelectedException;
import com.suthar.rentel.domain.util.NullObjectAddedException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
@Scope(value = "singleton")
@Component
public class SetBasedCustomerRepository implements CustomerRepository {
    @Autowired
    private CustomerService customerService;

    public void add(final Customer customer) throws NullObjectAddedException {
        if (customer == null) {
            throw new NullObjectAddedException();
        }
        customerService.saveCustomer(customer);
    }

    public void add(final Collection<Customer> customers) throws NullObjectAddedException {
        if (customers == null) {
            throw new IllegalArgumentException();
        }
        for (final Customer customer : customers) {
            if (customer == null) {
                throw new NullObjectAddedException();
            }
            customerService.saveCustomer(customer);
        }
    }

    public List<Customer> selectAll() {
        return customerService.getAllCustomers();
    }

    public List<Customer> selectAll(final Comparator<Customer> comparator) {
        List<Customer> result = customerService.getAllCustomers();
        Collections.sort(result, comparator);
        return result;
    }

    public List<Customer> selectSatisfying(final Specification<Customer> specification) {
        return selectSatisfyingIntoCollection(specification);
    }

    public List<Customer> selectSatisfying(final Specification<Customer> specification, final Comparator<Customer> comparator) {
        final List<Customer> result = selectSatisfyingIntoCollection(specification);
        Collections.sort(result, comparator);
        return result;
    }

    public Customer selectUnique(final Specification<Customer> specification) throws NonUniqueObjectSelectedException {
        final List<Customer> results = selectSatisfyingIntoCollection(specification);
        if (results.size() == 1) {
            return results.get(0);
        } else if (!results.isEmpty()) {
            throw new NonUniqueObjectSelectedException();
        }
        return null;
    }

    private List<Customer> selectSatisfyingIntoCollection(final Specification<Customer> specification) {
        List<Customer> target = new ArrayList<Customer>();
        for (Customer object : customerService.getAllCustomers()) {
            if (specification.isSatisfiedBy(object)) {
                target.add(object);
            }
        }
        return target;
    }
}

StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/repository/SetBasedMovieRepository.java
package com.suthar.rentel.domain.repository;

import com.suthar.rentel.domain.model.Movie;
import com.suthar.rentel.domain.service.MovieService;
import com.suthar.rentel.domain.specification.Specification;
import com.suthar.rentel.domain.util.NonUniqueObjectSelectedException;
import com.suthar.rentel.domain.util.NullObjectAddedException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.*;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
@Scope(value = "singleton")
@Component
public class SetBasedMovieRepository implements MovieRepository {
    @Autowired
    private MovieService movieService;

    public void add(final Movie entity) throws NullObjectAddedException {
        if (entity == null) {
            throw new NullObjectAddedException();
        }
        movieService.saveMovie(entity);
    }

    @Override
    public void add(final Collection<Movie> entities) throws NullObjectAddedException {
        if (entities == null) {
            throw new IllegalArgumentException();
        }
        for (final Movie entity : entities) {
            if (entity == null) {
                throw new NullObjectAddedException();
            }
            movieService.saveMovie(entity);
        }
    }

    @Override
    public List<Movie> selectAll() {
        return movieService.getAllMovies();
    }

    @Override
    public List<Movie> selectAll(final Comparator<Movie> comparator) {
        final List<Movie> result = movieService.getAllMovies();
        Collections.sort(result, comparator);
        return result;
    }

    @Override
    public List<Movie> selectSatisfying(final Specification<Movie> specification) {
        return selectSatisfyingIntoCollection(specification);
    }

    @Override
    public List<Movie> selectSatisfying(final Specification<Movie> specification, final Comparator<Movie> comparator) {
        final List<Movie> result = selectSatisfyingIntoCollection(specification);
        Collections.sort(result, comparator);
        return result;
    }

    @Override
    public Movie selectUnique(final Specification<Movie> specification) throws NonUniqueObjectSelectedException {
        final List<Movie> results = selectSatisfyingIntoCollection(specification);
        if (results.size() == 1) {
            return results.get(0);
        } else if (!results.isEmpty()) {
            throw new NonUniqueObjectSelectedException();
        }
        return null;
    }

    private List<Movie> selectSatisfyingIntoCollection(final Specification<Movie> specification) {
        List<Movie> target = new ArrayList<Movie>();
        for (Movie object : movieService.getAllMovies()) {
            if (specification.isSatisfiedBy(object)) {
                target.add(object);
            }
        }
        return target;
    }

    @Override
    public List<Movie> withTitles(String... titles) {
        return movieService.getMovies(titles);
    }
}

StrutsSpringHibernateDemoProject/videoworld08/src/main/java/com/suthar/rentel/domain/repository/SetBasedTransactionRepository.java
package com.suthar.rentel.domain.repository;

import com.suthar.rentel.domain.model.Customer;
import com.suthar.rentel.domain.model.Transaction;
import com.suthar.rentel.domain.specification.Specification;
import com.suthar.rentel.domain.specification.TransactionsForCustomerSpecification;
import com.suthar.rentel.domain.util.NullObjectAddedException;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.util.Collection;
import java.util.Comparator;
import java.util.Set;

/**
 * Rakesh Kumar Suthar (rksuthar19@gmail.com)
 */
@Scope(value = "singleton")
@Component
public class SetBasedTransactionRepository implements TransactionRepository {

    public SetBasedTransactionRepository() {
        super();
    }

    @Override
    public void add(Transaction entity) throws NullObjectAddedException {
        //To change body of implemented methods use File | Settings | File Templates.
    }

    @Override
    public void add(Collection<Transaction> entities) throws NullObjectAddedException {
        //To change body of implemented methods use File | Settings | File Templates.
    }

    @Override
    public Set<Transaction> selectAll() {
        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }

    @Override
    public Set<Transaction> selectAll(Comparator<Transaction> comparator) {
        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }

    @Override
    public Set<Transaction> selectSatisfying(Specification<Transaction> specification, Comparator<Transaction> comparator) {
        return null;  //To change body of implemented methods use File | Settings | File Templates.
    }

    @Override
    public Collection<Transaction> transactionsBy(Customer customer) {
        return selectSatisfying(new TransactionsForCustomerSpecification(customer), Transaction.TX_COMPARE_DATE_TIME);
    }
}

StrutsSpringHibernateDemoProject/videoworld08/src/main/webapp/admin.ftl
<html>
<head>
    <title>Administration</title>
</head>
<body>
<h1>Customers</h1>
<ul>
    <#list users as user>
    <li>${user.name}</li>
</#list>
</ul>
</body>
</html>

StrutsSpringHibernateDemoProject/videoworld08/src/main/webapp/history.ftl
<html>
<head>
    <title>Transaction History</title>
</head>
<body>
<h1>Transaction History</h1>
<ul>
<#list transactions as transaction>
    <li>Transaction on ${transaction.dateTime}<br/>
        Movies Rented:
        <#list transaction.rentals as rental>
        ${rental.movie.title}<#if rental_has_next>, </#if>
        </#list>
    </li>
</#list>
</ul>
</body>
</html>

StrutsSpringHibernateDemoProject/videoworld08/src/main/webapp/home.ftl
<html>
<head>
    <title>Rent a Movie</title>
    <link href="styles/wizard.css" rel="stylesheet" type="text/css"></link>
    <script type="text/javascript" src="js/wizard.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#wizard').wizard({
                validate: function (idx, elem) {
                    switch (idx) {
                        case 0:
                            if ($('input[name=movieNames]:checked').size() == 0) {
                                alert('Please select at least one movie');
                                return false;
                            }
                            return true;
                        case 2:
                            if ($('input[name=customerName]:checked').size() != 1) {
                                alert('Please select a customer');
                                return false;
                            }
                            return true;
                        default:
                            return true;
                    }
                }
            });
        });
    </script>
</head>
<body>
<h1>Rent a Movie</h1>

<form id="wizard" class="wiz-container" action="rentMovies">
    <ul class="wiz-list">
        <li><a href="#wizard-1">
            <h2>Now Showing!</h2>
            <small>Pick a movie</small>
        </a></li>
        <li><a href="#wizard-2"><h2>How long for?</h2>
            <small>Tell us how many days you want to rent for</small>
        </a></li>
    </ul>
    <div class="wiz-body">
        <div id="wizard-1">
            <div class="wiz-content movielist">
            <#list movies as movie>
                <div class="movie">
                    <p><input type="checkbox" name="movieNames" value="${movie.title}"/> ${movie.title}</p>
                </div>
            </#list>
            </div>
            <div class="wiz-nav">
                <input class="back btn" type="button" value="< Prev"/>
                <input class="next btn" type="button" value="Next >"/>
            </div>
        </div>
        <div id="wizard-2">
            <div class="wiz-content">
                <p>Number of days:
                    <select name="rentalDuration">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                        <option value="6">6</option>
                        <option value="7">7</option>
                    </select>
                </p>
            </div>
            <div class="wiz-nav">
                <input class="back btn" type="button" value="< Prev"/>
                <input class="done btn" type="submit" value="Done"/>
            </div>
        </div>
    </div>
</form>
</body>
</html>

StrutsSpringHibernateDemoProject/videoworld08/src/main/webapp/login.ftl
<html>
<head>
    <title>Login</title>
</head>
<body>
<h1>Login</h1>

<form id="login">
    <p>Select user:</p>
    <select class="customer" name="customerName">
    <#list customers as customer>
        <option value="${customer.name}">${customer.name}</option>
    </#list>
    </select>
    <input type="submit" value="login"/>
</form>
</body>
</html>

StrutsSpringHibernateDemoProject/videoworld08/src/main/webapp/rentals.ftl
<html>
<head>
    <title>Current Rentals</title>
</head>
<body>
<h1>Current Rentals</h1>
<ul>
<#list rentals as rental>
    <li>${rental.movie.title} (ends ${rental.endDate})</li>
</#list>
</ul>
</body>
</html>

StrutsSpringHibernateDemoProject/videoworld08/src/main/webapp/return.ftl
<html>
<head>
    <title>Rent a Movie</title>
    <link href="styles/wizard.css" rel="stylesheet" type="text/css"></link>
    <script type="text/javascript" src="js/wizard.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#wizard').wizard({
                validate: function (idx, elem) {
                    switch (idx) {
                        case 0:
                            if ($('input[name=movieNames]:checked').size() == 0) {
                                alert('Please select at least one movie');
                                return false;
                            }
                            return true;
                        case 2:
                            if ($('input[name=customerName]:checked').size() != 1) {
                                alert('Please select a customer');
                                return false;
                            }
                            return true;
                        default:
                            return true;
                    }
                }
            });
        });
    </script>
</head>
<body>
<h1>Return a Movie</h1>

<form id="wizard" class="wiz-container" action="returnMovies">
    <ul class="wiz-list">
        <li><a href="#wizard-1">
            <h2>Return Movies</h2>
            <small>Pick a movie to return</small>
        </a></li>
    </ul>
    <div class="wiz-body">
        <div id="wizard-1">
            <div class="wiz-content movielist">
            <#list rentals as r>
                <div class="movie">
                    <p><input type="checkbox" name="movieNames" value="${r.movie.title}"/> ${r.movie.title}</p>
                </div>
            </#list>
            </div>
            <div class="wiz-nav">
                <input class="back btn" type="button" value="< Cancel"/>
                <input class="done btn" type="submit" value="Done"/>
            </div>
        </div>
    </div>
</form>
</body>
</html>

StrutsSpringHibernateDemoProject/videoworld08/src/main/webapp/statement.ftl
<html>
<head>
    <title>Rental Statement</title>
</head>
<body>
<h1>Rental Statement</h1>
<pre>${statement}</pre>
</body>
</html>